name: xmlstream
version: 0.5.1
author: Joris Hermans <hermansj@gmail.com>
description: A streaming event-based XML Parser.
homepage: https://github.com/jorishermans/xmlstream
dependencies:
  unittest: '>=0.9.0 <0.9.1'
