name: xmlstream
version: 0.10.0
author: Joris Hermans <hermansj@gmail.com>
description: A streaming event-based XML Parser.
homepage: https://github.com/jorishermans/xmlstream
dependencies:
  event_stream: ">=0.3.2 <0.4.0"
dev_dependencies:
  test: '>=0.12.1 <0.12.2'
