name: xmlstream
version: 0.11.0
author: Joris Hermans <hermansj@gmail.com>
description: A streaming event-based XML Parser.
homepage: https://github.com/jorishermans/xmlstream
dev_dependencies:
  test: '>=1.5.1+1 <1.5.2'
  path: ^1.6.2
environment:
  sdk: '>=1.9.0 <3.0.0'